lslidar_driver_node:
  ros__parameters:
    lidar_type: "X10"
    lidar_model: "M10P"
    serial_port: "/dev/ttyUSB0"
    baud_rate: 460800

    frame_id: "laser_link"
    pointcloud_topic: "lslidar_point_cloud"
    laserscan_topic: "scan"

    publish_scan: true
    use_time_service: true
    use_first_point_time: false
    use_high_precision: false
    enable_noise_filter: false

    min_range: 0.15
    max_range: 50.0
    angle_disable_min: 0
    angle_disable_max: 0

    is_pretreatment: false
    is_MatrixTransformation: false
